server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialize: true
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  h2:
    console.enabled: true
    path: /h2-console
    settings.trace: false
    settings.web-allow-others: false
